export const APP_NAME = 'Chat App'
export const MAX_FILE_SIZE = 5 * 1024 * 1024 // 5MB
export const ALLOWED_FILE_TYPES = [
    'image/jpeg',
    'image/png',
    'image/gif',
]

export const DEFAULT_AVATAR =
    '/images/chatHeader/userAvatar.svg'

export const ContactsListDB = [
    {
        uid: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        username: 'string',
        nickname: '@vlaaad',
        phone: '987654321',
        firstName: 'Влад',
        lastName: 'Ляшев',
        patronymic: 'string',
        avatar: 'string',
        avatarUrl: 'AvatarWeb2.png',
        avatarWebp: 'string',
        avatarWebpUrl: 'string',
        additionalInformation: 'string',
        birthday: 0,
        chatId: 0,
        isOnline: true,
        wasOnlineAt: 0,
    },
    {
        uid: '3fa85f64-5717-4562-b3fc-2c963f66afa9',
        username: 'string',
        nickname: 'string',
        phone: '9132363070',
        firstName: 'Сергей',
        lastName: 'Авдиев',
        patronymic: 'string',
        avatar: 'string',
        avatarUrl: 'AvatarWeb1.png',
        avatarWebp: 'string',
        avatarWebpUrl: 'string',
        additionalInformation: 'string',
        birthday: 0,
        chatId: 0,
        isOnline: true,
        wasOnlineAt: 0,
    },
    {
        uid: '3fa85f64-5717-4562-b3fc-2c963f66afa8',
        username: 'string',
        nickname: 'string',
        phone: '777777777',
        firstName: 'Алла',
        lastName: 'Свиридова',
        patronymic: 'string',
        avatar: 'string',
        avatarUrl: 'AvatarWeb3.png',
        avatarWebp: 'string',
        avatarWebpUrl: 'string',
        additionalInformation: 'string',
        birthday: 0,
        chatId: 0,
        isOnline: false,
        wasOnlineAt: 0.5,
    },

    {
        uid: '3fa85f64-5717-4562-b3fc-2c963f66afa7',
        username: 'string',
        nickname: '@egor',
        phone: 'string',
        firstName: 'Егор',
        lastName: 'Петухов',
        patronymic: 'string',
        avatar: 'string',
        avatarUrl: 'AvatarWeb4.png',
        avatarWebp: 'string',
        avatarWebpUrl: 'string',
        additionalInformation: 'string',
        birthday: 0,
        chatId: 0,
        isOnline: false,
        wasOnlineAt: 25,
    },

    {
        uid: '3fa85f64-5717-4562-b3fc-2c963f66afb1',
        username: 'string',
        nickname: 'string',
        phone: 'string',
        firstName: 'Инна',
        lastName: 'Сивакова',
        patronymic: 'string',
        avatar: 'string',
        avatarUrl: 'AvatarWeb5.png',
        avatarWebp: 'string',
        avatarWebpUrl: 'string',
        additionalInformation: 'string',
        birthday: 0,
        chatId: 0,
        isOnline: false,
        wasOnlineAt: 1000,
    },

    {
        uid: '3fa85f64-5717-4562-b3fc-2c963f66afb2',
        username: 'string',
        nickname: 'string',
        phone: '91323655489',
        firstName: 'Артем',
        lastName: 'Галозин',
        patronymic: 'string',
        avatar: 'string',
        avatarUrl: 'AvatarWeb6.png',
        avatarWebp: 'string',
        avatarWebpUrl: 'string',
        additionalInformation: 'string',
        birthday: 0,
        chatId: 0,
        isOnline: false,
        wasOnlineAt: 48,
    },

    {
        uid: '3fa85f64-5717-4562-b3fc-2c963f66afb3',
        username: 'string',
        nickname: 'string',
        phone: '986525887',
        firstName: 'Татьяна',
        lastName: 'Пашина',
        patronymic: 'string',
        avatar: 'string',
        avatarUrl: 'AvatarWeb7.png',
        avatarWebp: 'string',
        avatarWebpUrl: 'string',
        additionalInformation: 'string',
        birthday: 0,
        chatId: 0,
        isOnline: false,
        wasOnlineAt: 1500,
    },

    {
        uid: '3fa85f64-5717-4562-b3fc-2c963f66afb9',
        username: 'string',
        nickname: 'string',
        phone: 'string',
        firstName: 'Евгений',
        lastName: 'Солнышков',
        patronymic: 'string',
        avatar: 'string',
        avatarUrl: 'AvatarWeb8.png',
        avatarWebp: 'string',
        avatarWebpUrl: 'string',
        additionalInformation: 'string',
        birthday: 0,
        chatId: 0,
        isOnline: false,
        wasOnlineAt: 3000,
    },

    {
        uid: '3fa85f64-5717-4562-b3fc-2c963f66afr5',
        username: 'string',
        nickname: 'string',
        phone: 'string',
        firstName: 'Анастасия',
        lastName: 'Христорождественская',
        patronymic: 'string',
        avatar: 'string',
        avatarUrl: 'AvatarWeb9.png',
        avatarWebp: 'string',
        avatarWebpUrl: 'string',
        additionalInformation: 'string',
        birthday: 0,
        chatId: 0,
        isOnline: false,
        wasOnlineAt: 5000,
    },
]

export const STATUS_TEXTS = {
    online: 'в сети',
    justNow: 'был(а) только что',
    minutesAgo: (minutes: number): string =>
        `был(а) ${minutes} минут назад`,
    hoursAgo: (hours: number): string =>
        `был(а) ${hours} часов назад`,
    yesterdayAt: (hours: string, minutes: string): string =>
        `был(а) вчера в ${hours}:${minutes}`,
    dateAgo: (date: string): string => `был(а) ${date}`,
} as const
