export const routes = {
  root: '/',
  chats: '/chats',
  chat: (id: string) => `/chats/${id}`,
  createGroup: '/chats/create/group',
  createChannel: '/chats/create/channel',
  contacts: '/contacts',
  settings: '/settings',
  profile: '/settings/profile',
  blacklist: '/settings/blacklist',
  support: '/settings/support',
  search: '/search',
  login: '/auth/login',
  register: '/auth/register',
  restore: '/auth/restore',
};
